python3 computer_vision_analysis.py model_training model1
python3 computer_vision_analysis.py model_training model2
python3 computer_vision_analysis.py model_training model3
python3 computer_vision_analysis.py model_training model4

